{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zitadel-access-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zitadel-access-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  zitadel-token: {{ .Values.zitadel.token | quote }}
  cloudflare-api-token: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}
